# This is a basic workflow that is manually triggered

name: Trigger eslint when merge

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
      branches: 
        - dev
        - todo/*
  pull_request:
      branches: 
        - dev
        - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  check-eslint:
    runs-on: ubuntu-latest
    name: Eslint checking
    strategy:
      matrix:
        node-version: ['20.x']
    steps:
      - name: Install Node.js runtime ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Node package
        run: npm install
  # This workflow contains a single job called "greet"
